# -*- coding: utf-8 -*-
"""carbon_emission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15BI83xJIOtXlvvEoYgRUdEvIPfJ97esL
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/Carbon Emission.csv')
print("DataFrame 'df' loaded successfully. First 5 rows:")
df.head()

df.info()

print("Missing values per column:")
df.isnull().sum()

df['Vehicle Type'].fillna('Not Applicable', inplace=True)
print("Missing values after imputation:")
df.isnull().sum()

categorical_cols = df.select_dtypes(include='object').columns
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)
print("DataFrame after one-hot encoding. First 5 rows:")
df_encoded.head()

X = df_encoded.drop('CarbonEmission', axis=1)
y = df_encoded['CarbonEmission']

print("Features (X) first 5 rows:")
print(X.head())
print("\nTarget (y) first 5 rows:")
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

print("Linear Regression model trained successfully.")

y_pred = model.predict(X_test)
print("Predictions generated successfully. First 5 predictions:")
print(y_pred[:5])

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(4, 4))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6, label='Predicted vs. Actual (Linear Regression)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions')
plt.legend()
plt.show()
print("Plot for actual vs. predicted carbon emissions displayed successfully.")

from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train, y_train)

import sklearn.preprocessing

results = {}

# Evaluate Linear Regression model
mae_lr = mean_absolute_error(y_test, y_pred)
mse_lr = mean_squared_error(y_test, y_pred)
r2_lr = r2_score(y_test, y_pred)

results['Linear Regression'] = {
    'MAE': mae_lr,
    'MSE': mse_lr,
    'R2': r2_lr
}

print("Linear Regression metrics stored in results dictionary.")

y_pred_ridge = ridge_model.predict(X_test)

# Evaluate Ridge Regression model
mae_ridge = mean_absolute_error(y_test, y_pred_ridge)
mse_ridge = mean_squared_error(y_test, y_pred_ridge)
r2_ridge = r2_score(y_test, y_pred_ridge)

results['Ridge Regression'] = {
    'MAE': mae_ridge,
    'MSE': mse_ridge,
    'R2': r2_ridge
}

print("Ridge Regression metrics stored in results dictionary.")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(4, 4))
sns.scatterplot(x=y_test, y=y_pred_ridge, alpha=0.6, label='Predicted vs. Actual (Ridge)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions (Ridge Regression)')
plt.legend()
plt.show()
print("Plot for actual vs. predicted carbon emissions for Ridge Regression displayed successfully.")

from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Lasso, ElasticNet, BayesianRidge

print("Necessary libraries for new regression models imported.")

poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

model_poly = LinearRegression()
model_poly.fit(X_train_poly, y_train)

y_pred_poly = model_poly.predict(X_test_poly)

mae_poly = mean_absolute_error(y_test, y_pred_poly)
mse_poly = mean_squared_error(y_test, y_pred_poly)
r2_poly = r2_score(y_test, y_pred_poly)

results['Polynomial Regression'] = {
    'MAE': mae_poly,
    'MSE': mse_poly,
    'R2': r2_poly
}

print("Polynomial Regression model trained and evaluated successfully.")
print(f"Mean Absolute Error (MAE): {mae_poly:.2f}")
print(f"Mean Squared Error (MSE): {mse_poly:.2f}")
print(f"R-squared (R2): {r2_poly:.2f}")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(4, 4))
sns.scatterplot(x=y_test, y=y_pred_poly, alpha=0.6, label='Predicted vs. Actual (Polynomial)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions (Polynomial Regression)')
plt.legend()
plt.show()
print("Plot for actual vs. predicted carbon emissions for Polynomial Regression displayed successfully.")

model_dt = DecisionTreeRegressor(random_state=42)
model_dt.fit(X_train, y_train)
y_pred_dt = model_dt.predict(X_test)

mae_dt = mean_absolute_error(y_test, y_pred_dt)
mse_dt = mean_squared_error(y_test, y_pred_dt)
r2_dt = r2_score(y_test, y_pred_dt)

results['Decision Tree Regression'] = {
    'MAE': mae_dt,
    'MSE': mse_dt,
    'R2': r2_dt
}

print("Decision Tree Regression model trained and evaluated successfully.")
print(f"Mean Absolute Error (MAE): {mae_dt:.2f}")
print(f"Mean Squared Error (MSE): {mse_dt:.2f}")
print(f"R-squared (R2): {r2_dt:.2f}")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(4, 4))
sns.scatterplot(x=y_test, y=y_pred_dt, alpha=0.6, label='Predicted vs. Actual (Decision Tree)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions')
plt.legend()
plt.show()
print("Decision Tree Plot for actual vs. predicted carbon emissions displayed successfully.")

model_rf = RandomForestRegressor(random_state=42)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)

mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

results['Random Forest Regression'] = {
    'MAE': mae_rf,
    'MSE': mse_rf,
    'R2': r2_rf
}

print("Random Forest Regression model trained and evaluated successfully.")
print(f"Mean Absolute Error (MAE): {mae_rf:.2f}")
print(f"Mean Squared Error (MSE): {mse_rf:.2f}")
print(f"R-squared (R2): {r2_rf:.2f}")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(4, 4))
sns.scatterplot(x=y_test, y=y_pred_rf, alpha=0.6, label='Predicted vs. Actual (Random Forest)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions')
plt.legend()
plt.show()
print("Random Forest Plot for actual vs. predicted carbon emissions displayed successfully.")

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Features scaled successfully for SVR model.")

model_sv = SVR(kernel='linear')
model_sv.fit(X_train_scaled, y_train)
y_pred_sv = model_sv.predict(X_test_scaled)

mae_sv = mean_absolute_error(y_test, y_pred_sv)
mse_sv = mean_squared_error(y_test, y_pred_sv)
r2_sv = r2_score(y_test, y_pred_sv)

results['Support Vector Regression'] = {
    'MAE': mae_sv,
    'MSE': mse_sv,
    'R2': r2_sv
}

print("Support Vector Regression model trained and evaluated successfully.")
print(f"Mean Absolute Error (MAE): {mae_sv:.2f}")
print(f"Mean Squared Error (MSE): {mse_sv:.2f}")
print(f"R-squared (R2): {r2_sv:.2f}")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred_sv, alpha=0.6, label='Predicted vs. Actual (Support Vector Regression)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions (Support Vector Regression)')
plt.legend()
plt.show()
print("Support Vector Regression Plot for actual vs. predicted carbon emissions displayed successfully.")

model_ls = Lasso(alpha=0.1)
model_ls.fit(X_train, y_train)
y_pred_ls = model_ls.predict(X_test)

mae_ls = mean_absolute_error(y_test, y_pred_ls)
mse_ls = mean_squared_error(y_test, y_pred_ls)
r2_ls = r2_score(y_test, y_pred_ls)

results['Lasso Regression'] = {
    'MAE': mae_ls,
    'MSE': mse_ls,
    'R2': r2_ls
}

print("Lasso Regression model trained and evaluated successfully.")
print(f"Mean Absolute Error (MAE): {mae_ls:.2f}")
print(f"Mean Squared Error (MSE): {mse_ls:.2f}")
print(f"R-squared (R2): {r2_ls:.2f}")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred_ls, alpha=0.1, label='Predicted vs. Actual (Lasso Regression)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions (Lasso Regression)')
plt.legend()
plt.show()
print("Lasso Regression Plot for actual vs. predicted carbon emissions displayed successfully.")

model_en = ElasticNet(alpha=0.1, l1_ratio=0.5)
model_en.fit(X_train, y_train)
y_pred_en = model_en.predict(X_test)

mae_en = mean_absolute_error(y_test, y_pred_en)
mse_en = mean_squared_error(y_test, y_pred_en)
r2_en = r2_score(y_test, y_pred_en)

results['ElasticNet Regression'] = {
    'MAE': mae_en,
    'MSE': mse_en,
    'R2': r2_en
}

print("ElasticNet Regression model trained and evaluated successfully.")
print(f"Mean Absolute Error (MAE): {mae_en:.2f}")
print(f"Mean Squared Error (MSE): {mse_en:.2f}")
print(f"R-squared (R2): {r2_en:.2f}")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred_en, alpha=0.6, label='Predicted vs. Actual (ElasticNet Regression)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions (ElasticNet Regression)')
plt.legend()
plt.show()
print("ElasticNet Regression Plot for actual vs. predicted carbon emissions displayed successfully.")

model_bl = BayesianRidge()
model_bl.fit(X_train, y_train)
y_pred_bl = model_bl.predict(X_test)

mae_bl = mean_absolute_error(y_test, y_pred_bl)
mse_bl = mean_squared_error(y_test, y_pred_bl)
r2_bl = r2_score(y_test, y_pred_bl)

results['Bayesian Regression'] = {
    'MAE': mae_bl,
    'MSE': mse_bl,
    'R2': r2_bl
}

print("Bayesian Regression model trained and evaluated successfully.")
print(f"Mean Absolute Error (MAE): {mae_bl:.2f}")
print(f"Mean Squared Error (MSE): {mse_bl:.2f}")
print(f"R-squared (R2): {r2_bl:.2f}")
print("\nFull results dictionary:")
print(results)

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred_bl, alpha=0.6, label='Predicted vs. Actual (Bayesian Regression)')

# Add a perfect prediction line
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--', lw=2, label='Perfect Prediction')

plt.xlabel('Actual Carbon Emission')
plt.ylabel('Predicted Carbon Emission')
plt.title('Actual vs. Predicted Carbon Emissions (Bayesian Regression)')
plt.legend()
plt.show()
print("Bayesian Regression Plot for actual vs. predicted carbon emissions displayed successfully.")